### ISSUE TITLE
JSHint error (from travis-ci)

### ISSUE THREAD

**Issue by khoipro** [khoipro/wpstarter#2]
```
0.33s$ if [[ "$LINT" == "1" ]]; then jshint --exclude ./vendor .; fi
assets/js/blocks.min.js: line 1, col 45, Expected '{' and instead saw 'return'.
assets/js/blocks.min.js: line 1, col 156, Missing semicolon.
assets/js/blocks.min.js: line 1, col 247, Missing semicolon.
assets/js/blocks.min.js: line 1, col 276, Strings must use singlequote.
assets/js/blocks.min.js: line 1, col 278, Expected '!==' and instead saw '!='.
assets/js/blocks.min.js: line 1, col 371, Strings must use singlequote.
assets/js/blocks.min.js: line 1, col 410, Strings must use singlequote.
assets/js/blocks.min.js: line 1, col 422, Missing semicolon.
```

Currently, this theme was packed with standardJS.
I need to confirm if it was shipped to wp.org, should we change `jshint` back to WP code standards?

Considering.

**Comment by khoipro** [comment]
@wturnerharris Can you advise the best way to handle it?

**Comment by wturnerharris** [comment]
As per [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/):
> The WordPress JavaScript Coding Standards are adapted from the [jQuery JavaScript Style Guide](https://contribute.jquery.org/style-guide/js/). Our standard differs from the jQuery guidelines in the following ways:
>
> - WordPress uses single quotation marks for string declarations.
> - Case statements are indented within switch blocks.
> - Function contents are consistently indented, including full-file closure wrappers.
> - Some whitespace rules differ, for consistency with the WordPress PHP coding standards.
> - jQuery’s 100-character hard line limit is encouraged, but not strictly enforced.

If this is being made to ship through the WordPress Plugins repo and be approved by WordPress, then you must follow all of their standards. Luckily you could simply run the fix command and most violations would be updated to jshint. You could script that if it works cleanly.
